keywords: Hexo,HTML,CSS,android,Linux
author: Author Name,name@example.com
description: Nothing lasts forever.
avatar: /images/favicon.png

twitter: 
rss: 
weibo: 
instagram: 
github: 

# Comment
duoshuo: 
disqus: 
gentie: 
